language: go

matrix:
  include:
    - os: linux
      go:
        - 1.10.x
        - 1.11.x
        - 1.12.x
      dist: xenial
    - os: osx
      go:
        - 1.10.x
        - 1.11.x
        - 1.12.x

before_install:
  - go get -v golang.org/x/lint/golint

script:
  - ./lint-unix.sh
  - go test ./...

